library(utils)
?time
#Menu Function
#draws and displays menu
# menuOptions = Takes arguements from objects generated by the "menulabel" function
# Displays..
# Your options:
#   1. ....
#   2. ....
#   3. Return to previous menu. (Break loop)
#   [Enter a number] (Waits for input)
# Error handling
# If not a recogized input, then display warning and loop again;
menuMaker<-function(menuOptions,
                    custom.return="Return to previous menu."){
  
  
  while(TRUE){
    
    #List menu options
    writeLines("+-------------------+") 
    writeLines("+ Your options are: +") 
    writeLines("+-------------------+") 
    for(i in 1:length(menuOptions[,1])){
      writeLines(paste(i,menuOptions[i,1]))
    }
    writeLines(paste((i+1),paste(custom.return)))
    
    #request User Input
    menuInput<-readline("[Enter a number] ")
    
    #Error Handling
    #inverse logic, if FALSE then TRUE
    if( (menuInput %in% 1:(i+1))==FALSE ){
      writeLines("Input not recognized. Please Try Again.")
      }
    
    #Return menu options
    else{
      cat("\014")  
      #Run menu option
      menuOptions1<- rbind(menuOptions,c('x',glob.return))
      menuOptions1[[as.numeric(menuInput),2]]()
      
      #break into outerloop
      if(menuInput==i+1){break}
    }
  }
}

glob.return<-function(){
  #filler
}

#Menu labeler
#Stores a String name and corresponding function that it should call if selected.
# name.list = Accepts list of strings for display in console for menu options
# func.list = list of functions (objects) that are called when referenced
# returns function
menuLabel<-function(name.list,func.list){
  names<-c(name.list)
  funcs<-c(func.list)
  labeled.menu<-cbind(names,funcs)
  return(labeled.menu)
}

#Useless loading animation
#loading bar animation
loadingBar<-function(speed=.1){
  for(i in 0:10)  {
    cat("\014")
    writeLines(

        paste("Loading [",
        strrep("=",i),
        strrep("-",10-i),
        "] ",round(i/10*100),"%",
        collapse = "",sep="")

    )
    Sys.sleep(speed)
  }
}


#clear text
#cat("\014") 

################################################################################
################################################################################
#Main Menu
#Code to create a custom menu
#Function for calling functions and returning to menu
################################################################################
################################################################################
# Option 1
main.op1<- function(){
  cat("\014") 
  writeLines(paste("Menu option 1",sep=''))
  
}
# Option 2
main.op2<-function(){
  cat("\014") 
  writeLines(
    "Menu option 2")
}
# Option 3
main.op3<-function(){
  cat("\014") 
  writeLines(
    "Menu option 3")
}
#Stores a String name and corresponding function that it should call if selected.
#names<-c("Option1",
#         "Option2")
#funcs<-c(main.op1,
#         main.op2)
#main.menu<-cbind(names,funcs)
main.menu<-menuLabel(c("op1","op2","op3"),c(main.op1, main.op2, main.op3))
menuMaker(main.menu)



#basic number guesser game

guess.me<-round(runif(1,1,3))

guess.1<- function(){
  cat("\014") 
  writeLines(paste("You guessed: 1",sep=''))
  writeLines(paste("",sep=''))
  if(guess.me == 1){
    writeLines(paste("You guessed RIGHT!!!!",sep=''))
  } else {
    writeLines(paste("You guessed WRONG!!!!",sep=''))
  }
  
}
guess.2<- function(){
  cat("\014") 
  writeLines(paste("You guessed: 2",sep=''))
  writeLines(paste("",sep=''))
  if(guess.me == 2){
    writeLines(paste("You guessed RIGHT!!!!",sep=''))
  } else {
    writeLines(paste("You guessed WRONG!!!!",sep=''))
  }
  
}

guess.3<- function(){
  cat("\014") 
  writeLines(paste("You guessed: 3",sep=''))
  writeLines(paste("",sep=''))
  if(guess.me == 3){
    writeLines(paste("You guessed RIGHT!!!!",sep=''))
  } else {
    writeLines(paste("You guessed WRONG!!!!",sep=''))
  }
  
}

guess.menu<-menuLabel(c("Guess 1","Guess 2","Guess 3"),
                     c(guess.1, guess.2, guess.3))
menuMaker(guess.menu,"Reset Number")



guess.start<- function(){
  cat("\014") 
  loadingBar()
  cat("\014") 
  writeLines(paste("Selcting a random number",sep=''))
  guess.me<<-round(runif(1,1,3))
  menuMaker(guess.menu,"Reset Number")
  
}

guess.start.menu<-menuLabel("Start",guess.start)
menuMaker(guess.start.menu,"Quit")



printme()




